# Project files have no CMake/Visual Studio files: just a JSON source manifest.
get_filename_component(config_file "${TINY3D_CONFIG}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
get_filename_component(config_directory "${config_file}" DIRECTORY)
if(NOT EXISTS "${config_file}" OR IS_DIRECTORY "${config_file}")
    message(FATAL_ERROR "Settings JSON not found: ${config_file}")
endif()
file(READ "${config_file}" settings)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${config_file}")

function(json_member output document member expected_type)
    string(JSON actual_type TYPE "${document}" "${member}")
    if(NOT actual_type STREQUAL expected_type)
        message(FATAL_ERROR "JSON member '${member}' must be ${expected_type}")
    endif()
    string(JSON value GET "${document}" "${member}")
    set(${output} "${value}" PARENT_SCOPE)
endfunction()

json_member(project_directory "${settings}" project STRING)
json_member(project_mode "${settings}" mode STRING)
if(NOT project_mode STREQUAL "editor" AND NOT project_mode STREQUAL "game")
    message(FATAL_ERROR "Mode must be 'editor' or 'game'")
endif()
string(JSON auto_start_type ERROR_VARIABLE auto_start_error TYPE "${settings}" autoStart)
set(project_auto_start ON)
if(NOT auto_start_error)
    json_member(project_auto_start "${settings}" autoStart BOOLEAN)
endif()
if(project_directory STREQUAL "")
    message(STATUS "No project selected; building the engine library only")
    return()
endif()
get_filename_component(project_directory "${project_directory}" ABSOLUTE BASE_DIR "${config_directory}")
set(manifest_file "${project_directory}/project.json")
if(NOT EXISTS "${manifest_file}" OR IS_DIRECTORY "${manifest_file}")
    message(FATAL_ERROR "Selected project must contain project.json: ${project_directory}")
endif()
file(READ "${manifest_file}" manifest)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${manifest_file}")
json_member(source_list "${manifest}" sources ARRAY)
string(JSON source_count LENGTH "${source_list}")
if(source_count EQUAL 0)
    message(FATAL_ERROR "project.json must list at least one C++ source file")
endif()
math(EXPR last_source "${source_count} - 1")
set(project_sources)
foreach(index RANGE ${last_source})
    string(JSON source_type TYPE "${source_list}" ${index})
    if(NOT source_type STREQUAL "STRING")
        message(FATAL_ERROR "Every sources entry must be a file path string")
    endif()
    string(JSON source GET "${source_list}" ${index})
    get_filename_component(source "${source}" ABSOLUTE BASE_DIR "${project_directory}")
    if(NOT EXISTS "${source}" OR IS_DIRECTORY "${source}")
        message(FATAL_ERROR "Project source does not exist: ${source}")
    endif()
    list(APPEND project_sources "${source}")
endforeach()

add_executable(tiny3d_project src/project_main.cpp ${project_sources})
target_link_libraries(tiny3d_project PRIVATE tiny3d)
target_include_directories(tiny3d_project PRIVATE "${project_directory}")
target_compile_definitions(tiny3d_project PRIVATE
    TINY3D_PROJECT_DIRECTORY="${project_directory}" TINY3D_PROJECT_MODE="${project_mode}")
message(STATUS "Active project: ${project_directory} (${project_mode})")

if(WIN32 AND NOT TINY3D_HEADLESS AND TINY3D_AUTO_START AND project_auto_start)
    find_program(TINY3D_POWERSHELL NAMES powershell REQUIRED)
    add_custom_target(tiny3d_launch ALL
        COMMAND "${TINY3D_POWERSHELL}" -NoProfile -ExecutionPolicy Bypass
            -File "${CMAKE_CURRENT_SOURCE_DIR}/Editor/launch.ps1"
            -Executable "$<TARGET_FILE:tiny3d_project>" -WorkingDirectory "${project_directory}"
        DEPENDS tiny3d_project
        VERBATIM)
endif()
