cmake_minimum_required(VERSION 3.19)
project(eryscript LANGUAGES CXX)
add_library(eryscript STATIC src/eryscript.cpp)
target_include_directories(eryscript PUBLIC include)
target_compile_features(eryscript PUBLIC cxx_std_17)
set_target_properties(eryscript PROPERTIES CXX_EXTENSIONS OFF)
if(MSVC)
    target_compile_options(eryscript PRIVATE /W4 /permissive-)
else()
    target_compile_options(eryscript PRIVATE -Wall -Wextra -Wpedantic)
endif()
